const  data = {
    data: {
      id: 1,
      full_name: 'Dev Account',
      email: 'dr-ahmed@v-verse.com',
      phone: '+20123456789',
      response_date: '2024-03-08T12:29:17.403625Z',
      is_online: false,
      custom_id: 'MBR-1',
      is_featured: false,
      email_verified_at: '2024-03-07T16:50:57.000000Z',
      phone_verified_at: '2024-03-07T16:50:57.000000Z',
      document_verified_at: '2024-03-07T16:50:57.000000Z',
      id_verified_at: '2024-03-07T16:50:57.000000Z',
      verification_status: 'approved',
      is_hide_welcome: 1,
      current_title: 'Current Title 1',
      current_company: 'Current Employer 1',
      counts: {
        sales_sum: 77,
        earned_sum: 61,
        jobs_count: 28,
        rating_avg: 63,
        rating_sum: 60,
        likes_count: 1,
        posts_count: 63,
        views_count: 15,
        events_count: 46,
        invested_sum: 36,
        no_of_assets: 62,
        orders_count: 75,
        points_count: 47,
        rating_count: 50,
        shares_count: 47,
        stores_count: 8,
        videos_count: 35,
        hirings_count: 49,
        members_count: 71,
        reviews_count: 29,
        channels_count: 72,
        comments_count: 57,
        dislikes_count: 68,
        projects_count: 48,
        services_count: 59,
        webinars_count: 12,
        customers_count: 84,
        followers_count: 13,
        applicants_count: 2,
        connections_count: 3,
        subscribers_count: 64,
        endorsements_count: 71,
        social_pages_count: 59,
        profile_likes_count: 72,
        social_groups_count: 3,
        profile_shares_count: 51,
        digital_products_count: 61,
        physical_products_count: 59
      },
      joining_date: '2024-03-07T16:50:46.000000Z',
      gender: 'Male',
      banner_tags: [],
      country: 'Aruba',
      residency: 'Aruba  -  oranjestad',
      time_zone: '-04:00',
      last_seen_at: '2024-03-07 16:50:46',
      is_connected: false,
      connection_status: 'approved',
      profile_type: 'personal',
      profile_id: 1,
      businessType: null,
      profile: {
        id: 1,
        legal_name: 'Dr Ahmed',
        public_name: 'Dr Ahmed',
        date_of_birth: '1981-03-07',
        is_custom_tagline: true,
        custom_tagline: 'This is a custom tagline',
        age: 43,
        gender: 'Male',
        nationality: 'Aruba',
        nationality_country_id: 1,
        residence_country: 'Aruba',
        residence_city: 'oranjestad',
        hobbies: 'Reading, Writing',
        location_longitude: '123.4560000',
        location_latitude: '78.9100000',
        employment_status: 'Employed',
        address: 'N/A',
        current_title: 'Current Title 1',
        current_employer: 'Current Employer 1',
        maps_url: 'https://maps.example.com',
        total_years_of_experience: 5,
        notice_period: 30,
        driving_license_enum: 'yes',
        service_rate_per_hour: '50.00',
        social_status_enum: 'Single',
        military_status_enum: 'Completed',
        excepected_gross_monthly_salary: '5000.00',
        phone: '1234567890',
        whatsapp: '1234567890',
        email: 'dr-ahmed@v-verse.com',
        website: 'https://www.example.com',
        is_featured: false,
        is_online: false,
        profile_message: 'This is the main profile message for User 1',
        weekly_hours_availability: 40,
        hourly_rate: '20.00',
        driving_license_issuing_country: 'Aruba',
        attachments: [],
        social_media_links: [Array],
        languages: [Array],
        resume: null,
        hiring_preferences: null,
        user_id: 1,
        related_entity_ids: [Array],
        related_entity_profiles_inside: [Array],
        profile_outside: null,
        residency: 'Aruba  -  oranjestad',
        v_guide_is_liked: false,
        v_blog_is_liked: false,
        v_jobs_is_liked: false
      },
      image: null,
      badges: [ [Object], [Object], [Object], [Object] ],
      plan_name: 'Vendor Plan',
      counts_text: 'v_verse_counts',
      is_my_account: true,
      v_guide_is_liked: false,
      v_blog_is_liked: false,
      v_jobs_is_liked: false,
      v_lance_is_liked: false,
      v_nation_is_liked: false,
      v_verse_is_liked: false,
      v_guide_is_saved: false,
      v_tube_is_liked: false,
      is_blocked: false,
      is_follower: true,
      is_reported: false,
      is_member: true,
      is_subscriber: false,
      is_candidate: false,
      is_applicant: false,
      is_client: false,
      v_blog_is_saved: false
    }
  }